# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_management', '0002_managedhost_login_password_managedhost_login_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='connected', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_command_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to='host_management.managedhost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
