# Generated by Codex on 2026-06-27

from django.db import migrations, models
from django.utils import timezone


DEFAULT_QUICK_COMMANDS = [
    ("Linux", "查看外网 IP", "curl cip.cc", "查看当前主机出口 IP"),
    ("Linux", "磁盘扩容", "lvresize -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv && resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv", "Ubuntu LVM 根分区扩容"),
    ("Linux", "查看磁盘读写", "iostat -dxm 1", "实时查看磁盘 IO"),
    ("Linux", "查看内存", "free -h", "查看内存使用情况"),
    ("Linux", "查看负载", "uptime && top -b -n 1 | head -20", "查看系统负载和进程概览"),
    ("Docker", "容器列表", "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'", "查看运行中的容器"),
    ("Docker", "查看 Docker 磁盘", "docker system df", "查看镜像、容器、卷占用"),
    ("Docker", "清理无用镜像", "docker image prune -f", "清理悬空镜像"),
    ("K8s", "Pod 列表", "kubectl get pods -A -o wide", "查看全部命名空间 Pod"),
    ("K8s", "节点状态", "kubectl get nodes -o wide", "查看集群节点"),
    ("K8s", "事件排序", "kubectl get events -A --sort-by=.metadata.creationTimestamp | tail -50", "查看最近事件"),
    ("网络", "监听端口", "ss -lntup", "查看监听端口和进程"),
    ("网络", "路由信息", "ip route && ip addr", "查看路由和网卡地址"),
    ("网络", "DNS 测试", "nslookup baidu.com", "测试 DNS 解析"),
]


def seed_quick_commands(apps, _schema_editor):
    TerminalQuickCommand = apps.get_model("web_terminal", "TerminalQuickCommand")
    if TerminalQuickCommand.objects.exists():
        return
    now = timezone.now()
    TerminalQuickCommand.objects.bulk_create(
        [
            TerminalQuickCommand(
                category=category,
                name=name,
                command=command,
                description=description,
                sort_order=index * 10,
                enabled=True,
                created_at=now,
                updated_at=now,
            )
            for index, (category, name, command, description) in enumerate(DEFAULT_QUICK_COMMANDS, start=1)
        ]
    )


def unseed_quick_commands(apps, _schema_editor):
    TerminalQuickCommand = apps.get_model("web_terminal", "TerminalQuickCommand")
    names = [name for _category, name, _command, _description in DEFAULT_QUICK_COMMANDS]
    TerminalQuickCommand.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("web_terminal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalQuickCommand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("command", models.TextField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="terminalquickcommand",
            index=models.Index(fields=["category", "sort_order"], name="web_termina_categor_f4c5d1_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalquickcommand",
            index=models.Index(fields=["enabled"], name="web_termina_enabled_bf4f2f_idx"),
        ),
        migrations.RunPython(seed_quick_commands, unseed_quick_commands),
    ]
