# Generated by Codex on 2026-07-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("host_management", "0010_remove_managedhost_unique_managed_host_private_ip"),
        ("web_terminal", "0002_terminalquickcommand"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminalsession",
            name="recording",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_last_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_cols",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_rows",
            field=models.PositiveSmallIntegerField(default=36),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_has_input",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TerminalCommandAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("command", models.TextField()),
                ("output", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("accept", "接受"), ("medium", "中风险"), ("high", "高风险")],
                        default="accept",
                        max_length=20,
                    ),
                ),
                ("asset_name", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("executed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_command_audits",
                        to="host_management.managedhost",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_audits",
                        to="web_terminal.terminalsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_command_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="terminalcommandaudit",
            index=models.Index(fields=["-executed_at", "-id"], name="web_termina_execute_21b4ee_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalcommandaudit",
            index=models.Index(fields=["risk_level", "-executed_at"], name="web_termina_risk_le_c7d90c_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalcommandaudit",
            index=models.Index(fields=["host", "-executed_at"], name="web_termina_host_id_0d2ee9_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalcommandaudit",
            index=models.Index(fields=["session", "-executed_at"], name="web_termina_session_54a138_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalcommandaudit",
            index=models.Index(fields=["username"], name="web_termina_usernam_7a859e_idx"),
        ),
    ]
