# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_terminal", "0003_terminal_session_audit_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminalsession",
            name="protocol",
            field=models.CharField(choices=[("ssh", "SSH"), ("rdp", "RDP")], default="ssh", max_length=20),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_file",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="recording_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="terminalsession",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
