# Generated by Django 5.2.16 on 2026-07-30 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(default='固定资产', max_length=80)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('spec', models.CharField(blank=True, max_length=260)),
                ('status', models.CharField(choices=[('using', '使用中'), ('idle', '闲置'), ('repair', '维修中')], default='using', max_length=20)),
                ('user', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('purchase_time', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='company_ass_status_91b2f7_idx'), models.Index(fields=['category'], name='company_ass_categor_ca563b_idx'), models.Index(fields=['code'], name='company_ass_code_8d23fb_idx')],
            },
        ),
    ]
