apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-tools-runtime-pvc
  namespace: default
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
