apiVersion: v1
kind: Service
metadata:
  name: devops-tools-app
  namespace: default
  labels:
    app: devops-tools
    component: app
spec:
  type: NodePort
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
      nodePort: 30001
  selector:
    app: devops-tools
    component: app
---
apiVersion: v1
kind: Service
metadata:
  name: devops-tools-ssh-gateway
  namespace: default
  labels:
    app: devops-tools
    component: ssh-gateway
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
      nodePort: 30222
  selector:
    app: devops-tools
    component: ssh-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: default
  labels:
    app: devops-tools
    component: guacd
spec:
  type: ClusterIP
  ports:
    - name: guacd
      port: 4822
      targetPort: guacd
      protocol: TCP
  selector:
    app: devops-tools
    component: guacd
