DEFAULT_LOG_RETENTION = {
    "loginLogsDays": 180,
    "operationLogsDays": 180,
    "terminalCommandAuditDays": 180,
    "terminalFileAuditDays": 180,
    "terminalSessionDays": 180,
    "rdpRecordingEnabled": False,
    "rdpRecordingDays": 30,
}

LOG_RETENTION_DAY_FIELDS = {
    "loginLogsDays",
    "operationLogsDays",
    "terminalCommandAuditDays",
    "terminalFileAuditDays",
    "terminalSessionDays",
    "rdpRecordingDays",
}

DEFAULT_TERMINAL_SETTINGS = {
    "sshConnectTimeoutSeconds": 15,
    "sshBannerTimeoutSeconds": 30,
    "sshAuthTimeoutSeconds": 20,
    "sshConnectAttempts": 3,
    "sshRetryDelayMs": 800,
    "sshKeepaliveSeconds": 30,
    "webSocketHeartbeatSeconds": 20,
    "idleDisconnectMinutes": 0,
    "initialReadTimeoutSeconds": 3,
    "initialReadIdleTimeoutMs": 350,
    "commandReadTimeoutSeconds": 30,
    "commandReadIdleTimeoutMs": 350,
    "readerPollIntervalMs": 30,
    "cwdHookSuppressEchoMs": 2000,
    "cwdHookDrainTimeoutMs": 800,
    "cwdHookDrainIdleTimeoutMs": 120,
    "defaultCols": 120,
    "defaultRows": 36,
    "defaultFontSize": 17,
    "scrollbackLines": 5000,
}

TERMINAL_SETTINGS_FIELD_LIMITS = {
    "sshConnectTimeoutSeconds": (1, 300),
    "sshBannerTimeoutSeconds": (1, 300),
    "sshAuthTimeoutSeconds": (1, 300),
    "sshConnectAttempts": (1, 10),
    "sshRetryDelayMs": (0, 10000),
    "sshKeepaliveSeconds": (0, 3600),
    "webSocketHeartbeatSeconds": (0, 3600),
    "idleDisconnectMinutes": (0, 1440),
    "initialReadTimeoutSeconds": (1, 60),
    "initialReadIdleTimeoutMs": (50, 10000),
    "commandReadTimeoutSeconds": (1, 3600),
    "commandReadIdleTimeoutMs": (50, 10000),
    "readerPollIntervalMs": (10, 1000),
    "cwdHookSuppressEchoMs": (0, 10000),
    "cwdHookDrainTimeoutMs": (100, 10000),
    "cwdHookDrainIdleTimeoutMs": (50, 10000),
    "defaultCols": (40, 300),
    "defaultRows": (10, 120),
    "defaultFontSize": (10, 24),
    "scrollbackLines": (100, 50000),
}
