import { useHostCredentials } from './useHostCredentials';
import { useHostEditor } from './useHostEditor';
import { useHostGroups } from './useHostGroups';
import { useHostImportExport } from './useHostImportExport';
import { useHostList, type HostManagerConfirm } from './useHostList';
import { useHostVerification } from './useHostVerification';

export { hostExportColumnOptions } from './useHostImportExport';
export type {
  HostExportColumnKey,
  HostExportColumnOption,
  HostExportOptions,
  HostExportScope,
  HostTransferFormat,
} from './useHostImportExport';

export function useHostManager({
  showToast,
  requestConfirm,
  currentUsername = () => null,
}: {
  showToast: (title: string, message: string) => void;
  requestConfirm: HostManagerConfirm;
  currentUsername?: () => string | null | undefined;
}) {
  const {
    hostCredentials,
    loadHostCredentials,
    replaceHostCredential,
    removeHostCredential,
    replaceHostCredentials,
  } = useHostCredentials();

  let hostList!: ReturnType<typeof useHostList>;
  const {
    selectedHostGroup,
    hostGroups,
    hostGroupRoot,
    flatHostGroups,
    visibleHostGroups,
    hostGroupRows,
    hostGroupRootExpanded,
    hostGroupInlineEdit,
    rootHostGroupDialogOpen,
    rootHostGroupName,
    rootHostGroupSortAfter,
    hostGroupMenu,
    draggedHostGroupId,
    hostGroupDropTarget,
    selectManagedGroup,
    hostGroupName,
    isHostGroupExpanded,
    toggleHostGroupExpanded,
    toggleHostGroupRootExpanded,
    startHostGroupDrag,
    updateHostGroupDropTarget,
    clearHostGroupDropTarget,
    dropHostGroup,
    finishHostGroupDrag,
    openHostGroupMenu,
    closeHostGroupMenu,
    openAddRootHostGroup,
    openAddHostGroup,
    openRenameHostGroup,
    saveHostGroupInlineEdit,
    saveRootHostGroup,
    cancelHostGroupInlineEdit,
    ensureDefaultHostGroup,
    deleteManagedHostsInGroup,
    deleteHostGroup,
    refreshGroupsOnly,
    replaceHostGroups,
    groupIdsFor,
    pruneCollapsedHostGroups,
  } = useHostGroups({
    showToast,
    requestConfirm,
    getManagedHosts: () => hostList.managedHosts.value,
    replaceManagedHosts: (hosts) => {
      hostList.managedHosts.value = hosts;
    },
    getManagedHostTotal: () => hostList.managedHostStats.value.total,
  });

  hostList = useHostList({
    showToast,
    requestConfirm,
    selectedHostGroup,
    groupIdsFor,
    loadHostCredentials,
    replaceHostGroups,
    replaceHostCredentials,
    pruneCollapsedHostGroups,
    refreshGroupsOnly,
  });
  const {
    hostSearch,
    hostStatusFilter,
    hostSortKey,
    hostSortDirection,
    managedHosts,
    isLoadingHosts,
    selectedManagedHostIds,
    visibleManagedHosts,
    managedHostStats,
    loadHostManagement,
    setHostSort,
    hostSortMark,
    deleteManagedHost,
    deleteSelectedManagedHosts,
    replaceHost,
  } = hostList;

  const {
    hostDialog,
    hostForm,
    hostFormErrors,
    hostMoveDialogOpen,
    hostMoveMode,
    hostMoveForm,
    groupMoveHosts,
    openWebTerminal,
    addManagedHost,
    editManagedHost,
    saveManagedHost,
    applyCredentialToHostForm,
    uploadHostPrivateKey,
    openMoveHostDialog,
    openMoveSelectedHostsDialog,
    saveMoveManagedHost,
  } = useHostEditor({
    showToast,
    currentUsername,
    selectedHostGroup,
    flatHostGroups,
    hostGroupMenu,
    closeHostGroupMenu,
    ensureDefaultHostGroup,
    refreshGroupsOnly,
    groupIdsFor,
    hostCredentials,
    loadHostCredentials,
    managedHosts,
    selectedManagedHostIds,
    replaceHost,
    hostSearch,
    hostStatusFilter,
  });

  const {
    verifyingHostIds,
    verifyManagedHost,
    verifyVisibleManagedHosts,
    verifySelectedManagedHosts,
  } = useHostVerification({
    showToast,
    managedHosts,
    visibleManagedHosts,
    selectedManagedHostIds,
    replaceHost,
  });

  const {
    backupHostManagement,
    exportHostManagement,
    importHostManagement,
  } = useHostImportExport({
    showToast,
    visibleManagedHosts,
    hostGroupName,
    loadHostManagement,
  });

  return {
    hostSearch,
    selectedHostGroup,
    hostStatusFilter,
    hostSortKey,
    hostSortDirection,
    hostGroups,
    hostCredentials,
    managedHosts,
    hostGroupRoot,
    flatHostGroups,
    visibleHostGroups,
    hostGroupRows,
    hostGroupRootExpanded,
    visibleManagedHosts,
    groupMoveHosts,
    managedHostStats,
    isLoadingHosts,
    hostGroupInlineEdit,
    rootHostGroupDialogOpen,
    rootHostGroupName,
    rootHostGroupSortAfter,
    hostGroupMenu,
    hostDialog,
    hostForm,
    hostFormErrors,
    hostMoveDialogOpen,
    hostMoveMode,
    hostMoveForm,
    draggedHostGroupId,
    hostGroupDropTarget,
    verifyingHostIds,
    selectedManagedHostIds,
    loadHostManagement,
    loadHostCredentials,
    replaceHostCredential,
    removeHostCredential,
    backupHostManagement,
    exportHostManagement,
    importHostManagement,
    selectManagedGroup,
    setHostSort,
    hostSortMark,
    hostGroupName,
    isHostGroupExpanded,
    toggleHostGroupExpanded,
    toggleHostGroupRootExpanded,
    startHostGroupDrag,
    updateHostGroupDropTarget,
    clearHostGroupDropTarget,
    dropHostGroup,
    finishHostGroupDrag,
    openHostGroupMenu,
    closeHostGroupMenu,
    openAddRootHostGroup,
    openAddHostGroup,
    openRenameHostGroup,
    saveHostGroupInlineEdit,
    saveRootHostGroup,
    cancelHostGroupInlineEdit,
    verifyManagedHost,
    verifyVisibleManagedHosts,
    verifySelectedManagedHosts,
    openWebTerminal,
    addManagedHost,
    editManagedHost,
    saveManagedHost,
    applyCredentialToHostForm,
    uploadHostPrivateKey,
    openMoveHostDialog,
    openMoveSelectedHostsDialog,
    saveMoveManagedHost,
    deleteManagedHost,
    deleteSelectedManagedHosts,
    deleteManagedHostsInGroup,
    deleteHostGroup,
  };
}
