# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0002_seed_builtin_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("module", models.CharField(max_length=80)),
                ("action", models.CharField(max_length=80)),
                ("target", models.CharField(blank=True, max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="system_mana_created_11c688_idx"),
                    models.Index(fields=["username"], name="system_mana_usernam_2302b7_idx"),
                    models.Index(fields=["module"], name="system_mana_module_020f5f_idx"),
                    models.Index(fields=["action"], name="system_mana_action_07cde2_idx"),
                ],
            },
        ),
    ]
