services:
  migrate:
    image: registry.cn-beijing.aliyuncs.com/kaikai136/devops-tools:v2.1.2-local-cache-cwdhook
    container_name: devops-tools-migrate
    restart: "no"
    init: true

    working_dir: /opt/devops-tools

    command:
      - /bin/sh
      - -c
      - |
        set -e
        mkdir -p /app/config /app/data /app/media /app/recordings
        python manage.py migrate --noinput

    volumes:
      - ./data:/app


  app:
    image: registry.cn-beijing.aliyuncs.com/kaikai136/devops-tools:v2.1.2-local-cache-cwdhook
    container_name: devops-tools
    restart: unless-stopped
    init: true

    depends_on:
      migrate:
        condition: service_completed_successfully

    environment:
      RUN_MIGRATE: "0"
      RUN_COLLECTSTATIC: "0"

      DJANGO_CSRF_TRUSTED_ORIGINS: "http://172.16.0.99:8088"

      SSH_GATEWAY_PUBLIC_HOST: "172.16.0.99"
      SSH_GATEWAY_PUBLIC_PORT: "2222"

    ports:
      - "8088:8001"
      - "2222:2222"

    volumes:
      - ./data:/app

    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS http://127.0.0.1:8001/api/health/ >/dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
