<script setup lang="ts">
import {
  Bell,
  Bookmark,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  Clipboard,
  Copy,
  CornerDownLeft,
  Cpu,
  Download,
  Edit3,
  Eye,
  EyeOff,
  File,
  Folder,
  FolderPlus,
  Gauge,
  Globe2,
  HardDrive,
  Image,
  Info,
  KeyRound,
  LayoutDashboard,
  Link,
  LockKeyhole,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Monitor,
  MoveRight,
  Network,
  Plus,
  QrCode,
  RefreshCw,
  ScrollText,
  RotateCcw,
  ScanLine,
  Search,
  Server,
  Settings,
  ShieldCheck,
  SquareTerminal,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from '@lucide/vue';
import { computed } from 'vue';

const props = withDefaults(defineProps<{ name: IconName; size?: number; strokeWidth?: number }>(), {
  size: 18,
  strokeWidth: 2,
});

const icons = {
  alert: CircleAlert,
  bell: Bell,
  bookmark: Bookmark,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsRight: ChevronsRight,
  circleCheck: CircleCheck,
  circleHelp: CircleHelp,
  circlePlus: CirclePlus,
  clipboard: Clipboard,
  copy: Copy,
  cornerDownLeft: CornerDownLeft,
  cpu: Cpu,
  dashboard: LayoutDashboard,
  download: Download,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  folder: Folder,
  folderPlus: FolderPlus,
  gauge: Gauge,
  globe: Globe2,
  hardDrive: HardDrive,
  image: Image,
  info: Info,
  key: KeyRound,
  link: Link,
  lock: LockKeyhole,
  logout: LogOut,
  maximize: Maximize2,
  menu: Menu,
  minimize: Minimize2,
  monitor: Monitor,
  moveRight: MoveRight,
  network: Network,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  scrollText: ScrollText,
  reset: RotateCcw,
  scan: ScanLine,
  search: Search,
  server: Server,
  settings: Settings,
  shield: ShieldCheck,
  terminal: SquareTerminal,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
};

export type IconName = keyof typeof icons;

const iconComponent = computed(() => icons[props.name]);
</script>

<template>
  <component
    :is="iconComponent"
    class="app-icon"
    :size="size"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
</template>
