# Generated by Codex on 2026-06-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("host_management", "0003_managedhost_verify_status"),
        ("web_terminal", "0002_terminalquickcommand"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityCommandRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                (
                    "match_type",
                    models.CharField(
                        choices=[("command", "Command"), ("regex", "Regex")],
                        default="command",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("ignore_case", models.BooleanField(default=True)),
                (
                    "action",
                    models.CharField(choices=[("block", "Block"), ("warn", "Warn")], default="block", max_length=20),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityCommandRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_name", models.CharField(blank=True, max_length=120)),
                ("command", models.TextField()),
                (
                    "action",
                    models.CharField(choices=[("block", "Block"), ("warn", "Warn")], max_length=20),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="host_management.managedhost"),
                ),
                (
                    "rule",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="security_tools.securitycommandrule"),
                ),
                (
                    "session",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="web_terminal.terminalsession"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="securitycommandrule",
            index=models.Index(fields=["enabled", "id"], name="security_to_enabled_87e9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="securitycommandrule",
            index=models.Index(fields=["match_type"], name="security_to_match_t_38d020_idx"),
        ),
        migrations.AddIndex(
            model_name="securitycommandrecord",
            index=models.Index(fields=["created_at"], name="security_to_created_130563_idx"),
        ),
        migrations.AddIndex(
            model_name="securitycommandrecord",
            index=models.Index(fields=["blocked"], name="security_to_blocked_56aeb6_idx"),
        ),
        migrations.AddIndex(
            model_name="securitycommandrecord",
            index=models.Index(fields=["action"], name="security_to_action_589900_idx"),
        ),
    ]
