# Generated by Django 5.2.15 on 2026-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedhost',
            name='login_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='managedhost',
            name='login_user',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='managedhost',
            name='port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='managedhost',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managedhost',
            name='private_key_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='managedhost',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HostCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('port', models.PositiveIntegerField(default=22)),
                ('private_key_name', models.CharField(blank=True, max_length=180)),
                ('private_key', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_host_credential_name')],
            },
        ),
    ]
