# Generated by Django 5.2.15 on 2026-06-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0004_managedhost_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedhost',
            name='os',
            field=models.CharField(choices=[('ubuntu', 'Ubuntu'), ('centos', 'CentOS'), ('debian', 'Debian'), ('windows', 'Windows')], default='centos', max_length=20),
        ),
    ]
