# Generated by Django 5.2.15 on 2026-06-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0009_managedhost_system_arch_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='managedhost',
            name='unique_managed_host_private_ip',
        ),
    ]
