# Generated by Codex on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host_management", "0010_remove_managedhost_unique_managed_host_private_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedhost",
            name="disk",
            field=models.CharField(blank=True, default="", max_length=260),
        ),
    ]
